format_version: 10
pipelines:
  cont-del:
    group: DD2482-Demo
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-5513184:
        git: https://github.com/oscols/DD2482-Demo
        shallow_clone: false
        auto_update: false
        branch: main
        webhook_secret: "devops1token8demo"
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-tests:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - README.md
                command: cat
                run_if: passed
